// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goframe-study/mall/internal/dao/internal"
)

// orderItemsDao is the data access object for the table order_items.
// You can define custom methods on it to extend its functionality as needed.
type orderItemsDao struct {
	*internal.OrderItemsDao
}

var (
	// OrderItems is a globally accessible object for table order_items operations.
	OrderItems = orderItemsDao{internal.NewOrderItemsDao()}
)

// Add your custom methods and functionality below.
