// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goframe-study/mall/internal/dao/internal"
)

// productsDao is the data access object for the table products.
// You can define custom methods on it to extend its functionality as needed.
type productsDao struct {
	*internal.ProductsDao
}

var (
	// Products is a globally accessible object for table products operations.
	Products = productsDao{internal.NewProductsDao()}
)

// Add your custom methods and functionality below.
