// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package debug

import (
	"goframe-study/mall/api/debug"
)

type ControllerV1 struct{}

func NewV1() debug.IDebugV1 {
	return &ControllerV1{}
}
